name: ViaEcoSmpDiemDanh
version: '1.0'
main: org.kazamistudio.dailyReward.DailyReward
api-version: '1.20'
load: STARTUP
authors: [ Kazami Studio ]
description: Plugin với đầy đủ các chức năng mở rộng mà bạn có thể tuỳ biến cao

depend: [Vault, PlaceholderAPI]

commands:
  diemdanh:
    description: Mở GUI điểm danh
  ngaybu:
    description: Mở GUI điểm danh lại
  dallyreload:
    description: Reload file config
    permission: dailyreward.admin
permissions:
  dailyreward.admin:
    default: op